steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lotto-number-app', '-f', 'Dockerfile', '.']
    dir: 'lottoNumber'
images:
  - 'gcr.io/$PROJECT_ID/lotto-number-app'