#name: Deploy to Google Cloud Run
#
#on:
#  push:
#    branches:
#      - main  # main 브랜치에 푸시할 때 실행
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Google Cloud CLI
#        uses: google-github-actions/setup-gcloud@v2
#        with:
#          project_id: ${{ secrets.GCP_PROJECT_ID }}
#          service_account_key: ${{ secrets.GCP_SA_KEY }}  # 서비스 계정 키를 GitHub Secrets에 추가해야 함
#
#      - name: Build Docker image
#        run: |
#          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/lotto-number-app ./lottoNumber
#
#      - name: Push Docker image
#        run: |
#          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/lotto-number-app
#
#      - name: Deploy to Cloud Run
#        run: |
#          gcloud run deploy lotto-number-app \
#            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/lotto-number-app \
#            --platform managed \
#            --region ${{ secrets.GCP_REGION }} \
#            --allow-unauthenticated